kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  namespace: lgp-formacion
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: ibm-spectrum-scale-csi-consistency-group-delete
  volumeMode: Filesystem
